python gpx_streetview.py ..\RouteExplorer\Routes\ADV04_Bages-St-Paul
python gpx_streetview.py ..\RouteExplorer\Routes\ADV05_St-Paul-Rennes-les-Bains
python gpx_streetview.py ..\RouteExplorer\Routes\ADV06_Rennes-les-Bains-Bram
python gpx_streetview.py ..\RouteExplorer\Routes\ADV07_Bram-St_Felix
python gpx_streetview.py ..\RouteExplorer\Routes\ADV08_StFelix_Gaillac
python gpx_streetview.py ..\RouteExplorer\Routes\ADV09_Gaillac-St_Antonin
python gpx_streetview.py ..\RouteExplorer\Routes\ADV10_St_Antonin-Cajarc
python gpx_streetview.py ..\RouteExplorer\Routes\ADV11_Cajarc-Cahors
python gpx_streetview.py ..\RouteExplorer\Routes\ADV12_Cahors-Gourdon
python gpx_streetview.py ..\RouteExplorer\Routes\ADV13_Gourdon-Sarlat
python gpx_streetview.py ..\RouteExplorer\Routes\ADV14_EyziesLoop
python gpx_streetview.py ..\RouteExplorer\Routes\ADV15_Sarlat_Beynac
python gpx_streetview.py ..\RouteExplorer\Routes\ADV17_Beynac_Coux
python gpx_streetview.py ..\RouteExplorer\Routes\ADV18_LeCoux_Monpazier
python gpx_streetview.py ..\RouteExplorer\Routes\ADV19_Monpazier_VillsurLot
python gpx_streetview.py ..\RouteExplorer\Routes\ADV20_ShortVillsurLot_Agen
python gpx_streetview.py ..\RouteExplorer\Routes\ADV20_VillsurLot_Agen
python gpx_streetview.py ..\RouteExplorer\Routes\ADV21_Agen_Moissac
python gpx_streetview.py ..\RouteExplorer\Routes\ADV22_Moissac_Toulouse
python gpx_streetview.py ..\RouteExplorer\Routes\G26-1_El_Far
python gpx_streetview.py ..\RouteExplorer\Routes\G26-10_BikeBreaksPlus
python gpx_streetview.py ..\RouteExplorer\Routes\G26-11_Olot
python gpx_streetview.py ..\RouteExplorer\Routes\G26-12_MdddM
python gpx_streetview.py ..\RouteExplorer\Routes\G26-13_El_Far_Vic
python gpx_streetview.py ..\RouteExplorer\Routes\G26-14_Hincapie_BikeBreaks
python gpx_streetview.py ..\RouteExplorer\Routes\G26-15_San_Marti_Empuries
python gpx_streetview.py ..\RouteExplorer\Routes\G26-2_El_Far_Olot
python gpx_streetview.py ..\RouteExplorer\Routes\G26-3_El_Far_short
python gpx_streetview.py ..\RouteExplorer\Routes\G26-4_Sant_Hilari
python gpx_streetview.py ..\RouteExplorer\Routes\G26-5_Tossa
python gpx_streetview.py ..\RouteExplorer\Routes\G26-6_Tossa
python gpx_streetview.py ..\RouteExplorer\Routes\G26-7_Hincapie
python gpx_streetview.py ..\RouteExplorer\Routes\G26-8_Sant_Hilari
python gpx_streetview.py ..\RouteExplorer\Routes\G26-9_BikeBreaks
